"""empty message

Revision ID: 275585394e6b
Revises: d2c48b212fce
Create Date: 2023-12-26 16:52:06.786534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275585394e6b'
down_revision = 'd2c48b212fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('result_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_unique_constraint('result_email_key', ['email'])
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
