"""empty message

Revision ID: 7b8619ff3800
Revises: 788475c071b8
Create Date: 2023-12-21 15:37:07.163553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8619ff3800'
down_revision = '788475c071b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('no_of_questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('result', sa.Enum('visible', 'hidden', name='result_visibility'), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('token')
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('result')
        batch_op.drop_column('no_of_questions')
        batch_op.drop_column('duration')
        batch_op.drop_column('exam_type')

    # ### end Alembic commands ###
