"""empty message

Revision ID: cd498b483fb6
Revises: 7b8619ff3800
Create Date: 2023-12-25 23:13:13.172272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd498b483fb6'
down_revision = '7b8619ff3800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', postgresql.ENUM('visible', 'hidden', name='result_visibility'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
