"""empty message

Revision ID: d2c48b212fce
Revises: cd498b483fb6
Create Date: 2023-12-26 11:09:49.658496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c48b212fce'
down_revision = 'cd498b483fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Enum('visible', 'hidden', name='result_visibility'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
